---
AWSTemplateFormatVersion: '2010-09-09'
Description: Create a variable number of EC2 instance resources.
Parameters:
  InstanceCount:
    Description: Number of EC2 instances (must be between 1 and 10).
    Type: Number
    Default: 10
    MinValue: 1
    MaxValue: 10
    ConstraintDescription: Must be a number between 1 and 10.
  ImageId:
    Description: Image ID to launch EC2 instances.
    Type: AWS::EC2::Image::Id
    # amzn-ami-hvm-2016.09.1.20161221-x86_64-gp2
    Default: ami-0cc96feef8c6bbff3
    AllowedValues: [ ami-0cc96feef8c6bbff3, ami-024a64a6685d05041, ami-07b4156579ea1d7ba ]
  InstanceType:
    Description: Instance type to launch EC2 instances.
    Type: String
    Default: t2.micro
    AllowedValues: [ t2.micro, m3.large, m3.xlarge, m3.2xlarge ]
Conditions:
  Launch10: !Equals [10, !Ref InstanceCount]
  Launch9: !Or
  - !Equals [9, !Ref InstanceCount]
  - !Condition Launch10
  Launch8: !Or
  - !Equals [8, !Ref InstanceCount]
  - !Condition Launch9
  Launch7: !Or
  - !Equals [7, !Ref InstanceCount]
  - !Condition Launch8
  Launch6: !Or
  - !Equals [6, !Ref InstanceCount]
  - !Condition Launch7
  Launch5: !Or
  - !Equals [5, !Ref InstanceCount]
  - !Condition Launch6
  Launch4: !Or
  - !Equals [4, !Ref InstanceCount]
  - !Condition Launch5
  Launch3: !Or
  - !Equals [3, !Ref InstanceCount]
  - !Condition Launch4
  Launch2: !Or
  - !Equals [2, !Ref InstanceCount]
  - !Condition Launch3
  Launch1: !Or
  - !Equals [1, !Ref InstanceCount]
  - !Condition Launch2
Resources:
  Instance1:
    Condition: Launch1
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
  Instance2:
    Condition: Launch2
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
  Instance3:
    Condition: Launch3
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
  Instance4:
    Condition: Launch4
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
  Instance5:
    Condition: Launch5
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
  Instance6:
    Condition: Launch6
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
  Instance7:
    Condition: Launch7
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
  Instance8:
    Condition: Launch8
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
  Instance9:
    Condition: Launch9
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
  Instance10:
    Condition: Launch10
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType